### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by visiOOnbyRJ** [davidmathers/tokyo-night-kitty-theme#1]
Hey man beautiful port!!! I am trying to find a way to add without polluting my kitty.conf, so i made a theme.conf and added ur config! for the death of me it is not working. Can you provide me with a little guidance. i added `include ./theme.conf` to the top as well

**Comment by davidmathers** [comment]
That sounds like it should work. I recommend trying this first:

1. copy ```tokyo-night-kitty.conf``` to ```~/.config/kitty/```
2. add ```include tokyo-night-kitty.conf``` as the last line in ```~/.config/kitty/kitty.conf```

That's how I currently use the color scheme.

**Comment by visiOOnbyRJ** [comment]
i just gave up, restarted my computer a couple days later and it worked lmao! I cant debug to help other people. Beautiful theme btw!!
